main: com.dreamcove.minecraft.raids.RaidsPlugin
name: PartyRaids
version: 1.0.0
author: vaporofnuance
api-version: 1.16
load: POSTWORLD
depend:
  - Parties
permissions:
  raids.help:
    description: Allows player to ask for help
    default: true
  raids.start:
    description: Allows starting a command
    default: true
  raids.cancel:
    description: Allows party members to cancel a raid before starting
    default: true
  raids.exit:
    description: Allows party members to exit the raid
    default: true
  raids.end:
    description: Allows party members to end the raid
    default: true
  raids.reload:
    description: Allows for reload of plugin configuration
    default: op
  raids.edit:
    description: Allows for editing of dungeon levels
    default: op
  raids.save:
    description: Allows for saving current level being edited
    default: op
commands:
  raids:
    description: Manage party raids
    usage: /raids help
